// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7du0pEDczrYsOCw9t7TMNSeqP_yX0SHo',
    appId: '1:1072774806117:web:7d833a9f7bd712c288248c',
    messagingSenderId: '1072774806117',
    projectId: 'phone-authentication-b115b',
    authDomain: 'phone-authentication-b115b.firebaseapp.com',
    storageBucket: 'phone-authentication-b115b.appspot.com',
    measurementId: 'G-LM7G45TLQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUltXBvFH7L7pvV5qrwJNr04w5ZNhtyQ',
    appId: '1:1072774806117:android:b59ddcf281c3a74d88248c',
    messagingSenderId: '1072774806117',
    projectId: 'phone-authentication-b115b',
    storageBucket: 'phone-authentication-b115b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB99r57BZVRCjsrtX5dK7d9sh6kVC9cVU',
    appId: '1:1072774806117:ios:2128981db897ddcf88248c',
    messagingSenderId: '1072774806117',
    projectId: 'phone-authentication-b115b',
    storageBucket: 'phone-authentication-b115b.appspot.com',
    iosClientId: '1072774806117-2ndves58332rvbkuhvacpdoplm2ldsf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB99r57BZVRCjsrtX5dK7d9sh6kVC9cVU',
    appId: '1:1072774806117:ios:2128981db897ddcf88248c',
    messagingSenderId: '1072774806117',
    projectId: 'phone-authentication-b115b',
    storageBucket: 'phone-authentication-b115b.appspot.com',
    iosClientId: '1072774806117-2ndves58332rvbkuhvacpdoplm2ldsf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthentication',
  );
}
